[build]
  base = "/"  # โฟลเดอร์หลักของโปรเจกต์ทั้งหมด
  command = "cd app && npm run build"  # เข้าไปในโฟลเดอร์ app ก่อนแล้วค่อย build
  publish = "build/client" 
  
[functions]
  directory = "netlify/functions" 

[[redirects]]
from = "/*"
to = "/index.html"
status = 200