[build]
  base = "app/"
  command = "npm run build"
  publish = "build/client" # ปรับตามโครงสร้างของโปรเจกต์คุณ
  
[functions]
  directory = "netlify/functions" 

[[redirects]]
from = "/*"
to = "/index.html"
status = 200